name: Deploy to production

on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: erp-backend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g3h6f1a5
        docker build -t public.ecr.aws/g3h6f1a5/erp-backend:$IMAGE_TAG -t public.ecr.aws/g3h6f1a5/erp-backend:latest .
        docker push -a public.ecr.aws/g3h6f1a5/erp-backend
